// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ixiaqxshkiubfbsgzqrr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4aWFxeHNoa2l1YmZic2d6cXJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ2MTg5NTEsImV4cCI6MjA1MDE5NDk1MX0.KukZJs_9oSWjaaQ3mho-OOXm-k987UeyqjGkt4B90Rw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);